import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import {  Tab, Tabs } from '@/components/tab-wrapper'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
      <button><Link href={'/Test'}>Test</Link></button>
      </nav>
 
      <main className={`${styles.main} ${inter.className}`}>
        Default assigned props are not available in firstUpdate Component
        <Tabs variant="test">
          <Tab title="Tab1"></Tab>
          <Tab title="Tab2"></Tab>
        </Tabs>
      </main>
    </>
  )
}
